### PR TITLE
Add support for preview of React elements

### PR DESCRIPTION
**Pull request by hex13**
I made a preview feature for React elements:

I mean. It looked this way:
image

Now when Mancy detects React element it renders a preview:
image

### CODE REVIEW

**Comment by princejwesley** [comment]
@hex13 Thanks for your PR.

Instead of eliminating the ReactElement View, Its good to show it as it is.
Revised the code adds a tag like we render HTML string (shown below) along with object view and made use of [ReplOutputHTML](https://github.com/princejwesley/Mancy/blob/master/src/components/ReplOutputHTML.js). I ignored invalid react element which might screw up the whole application.

image

**Comment by hex13** [comment]
Yeah. I see. I didn’t know that in Mancy there was already preview HTML feature and you're probably right (my class `ReplOutputReactElement` was nice but was also reinventing a wheel in the context of the previous code).

One thing is bugging me though - I don’t know if injecting `{reactElementView}` to generic `ReplOutputObject` class is proper. What if we wanted later to render other components, e.g. Angular components?

What if code in next versions would look like code below?
```javascript

render() {
 let label = ReplCommon.highlight(this.props.label || this.getType(this.props.object));
 let reactElementView = this.reactElementView();
 let angularElementView = this.angularElementView();
 let emberElementView = this.emberElementView(); // some other frameworks
 let vueElementView = this.vueElementView();
 // ...

 ? <span className='repl-entry-message-output-object'>
                 <i className='fa fa-play' onClick={this.onToggleCollapse}></i>
                 <span className='object-desc' dangerouslySetInnerHTML={{__html:label}}></span>
                {reactElementView}
                {angularElementView}
                {emberElementView}
                {vueElementView}
```
I mean this could be become a little bit messy.

**Comment by princejwesley** [comment]
`ReplOutputObject` is for common object view with extra possible visualisations(not just one but multiple).

If you look at your example closely, you will notice that all are mutually exclusive!. Also I would place it to [DOM](https://github.com/princejwesley/Mancy/commit/6380184951811d4383a890b404f973bf7497e656) handler file if it grows.

Honestly, I am not interested in rendering various html frameworks like as angular or ember. React view is exception since this app is built on it(no new/extra dependency). Object label is a visual aid for React like special object without introducing new dependency.

Appreciate your effort!

**Comment by princejwesley** [comment]
I accept that the documentation is poor. At the moment, most of the features are like hidden gem :smile:

**Comment by hex13** [comment]
`React view is exception since this app is built on it(no new/extra dependency).`
I think that having plugin system would be great help. Then if somebody is interested in e.g. Angular, then this person could make plugin for Mancy with additional Angular dependency etc..
(related to https://github.com/princejwesley/Mancy/issues/34 )
There would be no mess in the Mancy itself, but there would be still possibility to make this particular feature.

**Comment by princejwesley** [comment]
Agreed.

**Pull request merged**
